### PR TITLE
Update to cxx 1.0

### PR DESCRIPTION
**Pull request by dtolnay**

### CODE REVIEW

**Comment by berquist** [comment]
Thank you @dtolnay for doing this and writing the crate. Regarding

> The previous implementation failed to compile on my machine.

this is because the definition is (like most of the library) auto-generated at compile time; first, a compiler compiler is generated, and then a whole slew of architecture-specific source code is auto-generated based on configuration parameters, then compiled. Proper dependency detection and/or generation will have to wait...

I have a question about wrapping types as opaque blobs, specifically the `Engine` class in `/usr/include/libint2/engine.h`. I tried https://github.com/berquist/libint2.rs/blob/a15e31020596bd81412f002d0a1ac31111c07bca/include/libint2_wrapper.hpp#L14 but get the C++ compiler complaint
```
error: 'Engine' in namespace '::' does not name a type
  using Engine = ::Engine;
```
I'm not sure this is the correct solution in the short or long term, but want to keep as much Rust-side as possible. Do you have any ideas?

**Comment by dtolnay** [comment]
The generated code ("libint2/src/lib.rs.h") needs everything you put inside `extern "C++"` to be declared (not necessarily defined).

Your header "include/libint2_wrapper.hpp" **starts with** `#include "libint2/src/lib.rs.h"`. It declares LibintEngine *after* that, but stuff declared *after* `#include "libint2/src/lib.rs.h"` would not exist from the point of view of the generated code.

**Comment by dtolnay** [comment]
The simplest fix would be to add:

```diff
  unsafe extern "C++" {
+     include!("libint2/engine.h");

+     #[namespace = "libint2"]
+     type Engine;
  }
```

**Comment by berquist** [comment]
D'oh, thanks!

**Pull request merged**
